#!/bin/sh
# parameterize_env.sh - Extract env defaults from config files and sync to .env / .env.example
#
# Usage:
#   parameterize_env.sh                        # normal mode (preserve .env overrides)
#   parameterize_env.sh --force                # overwrite .env with code defaults
#   parameterize_env.sh [--force] config.py assumption_config.py   # custom paths

set -e

force=0
if [ "$1" = "--force" ]; then
    force=1
    shift
fi

script_dir="$(dirname "$0")"
awk_script="$script_dir/extract_env.awk"

# Default config files (relative to script location)
# script_dir = src/shell/ ; .. = src/ ; ../python/ = src/python/
config1="${1:-$script_dir/../python/config.py}"
config2="${2:-$script_dir/../python/assumption_config.py}"

envfile=".env"
examplefile=".env.example"

# Step 1: Extract KEY=DEFAULT from config files.
# Dedup with last-wins so assumption_config.py values override config.py's ASSUMPTION_* references.
extracted=$(awk -f "$awk_script" "$config1" "$config2" | awk -F= '
    { vals[$1] = $0 }
    END { for (k in vals) print vals[k] }
')

# Bail early if nothing extracted
if [ -z "$extracted" ]; then
    echo "parameterize_env.sh: no env vars extracted (check config file paths)" >&2
    exit 1
fi

# Step 2: Update .env.example — replace matching keys, add new ones, preserve comments.
echo "$extracted" | awk -F= '
    FNR == NR {
        extracted[$1] = $0
        next
    }
    /^[A-Za-z_][A-Za-z0-9_]*=/ {
        key = $1
        if (key in extracted) {
            print extracted[key]
            seen[key] = 1
            next
        }
    }
    { print }
    END {
        for (k in extracted)
            if (!(k in seen)) print extracted[k]
    }
' - "$examplefile" > "$examplefile.tmp" && mv "$examplefile.tmp" "$examplefile"

# Step 3: Update .env
if [ "$force" -eq 1 ]; then
    # Force mode: same logic as .env.example — overwrite matching keys
    echo "$extracted" | awk -F= '
        FNR == NR {
            extracted[$1] = $0
            next
        }
        /^[A-Za-z_][A-Za-z0-9_]*=/ {
            key = $1
            if (key in extracted) {
                print extracted[key]
                seen[key] = 1
                next
            }
        }
        { print }
        END {
            for (k in extracted)
                if (!(k in seen)) print extracted[k]
        }
    ' - "$envfile" > "$envfile.tmp" && mv "$envfile.tmp" "$envfile"
else
    # Normal mode: only append keys NOT already in .env
    if [ -f "$envfile" ]; then
        # Read existing keys, append missing ones
        new_keys=$(echo "$extracted" | awk -F= '
            FNR == NR { existing[$1] = 1; next }
            !($1 in existing) { print }
        ' "$envfile" -)
        if [ -n "$new_keys" ]; then
            printf "\n# Added by parameterize_env.sh\n%s\n" "$new_keys" >> "$envfile"
        fi
    else
        # No .env file — create it with all extracted defaults
        printf "# Generated by parameterize_env.sh\n%s\n" "$extracted" > "$envfile"
    fi
fi
