name: Python Coverage and Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Coverage Test

    steps:
    - uses: actions/checkout@v4

    - name: Cache conda environment
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: 'latest'
        environment-file: environment.yml
        activate-environment: ABM

    - name: Create .env file for testing
      run: |
        if [ -f .env.example ]; then cp .env.example .env; fi

    - name: Run tests with coverage
      run: |
        # Activate conda environment and run tests
        source ${{ env.CONDA }}/etc/profile.d/conda.sh
        conda activate ABM
        echo "Python path: $(which python)"
        echo "Python version: $(python --version)"
        echo "Conda environment: $(conda env list)"
        python -c "import pytest; print('pytest version:', pytest.__version__)"
        python -m pytest -m "not config" -v
        python -m pytest -m "config" --no-cov -v
