name: Render Demos

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    name: Quarto Render Demos
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0
        with:
          activate-environment: true
      - name: Render demos
        run: pixi run quarto src/python/demos/